var img, x, y; // Declare variables...
function preload() {
  // Preload the image before the program starts...
  img = loadImage("Squareptrn.png"); // Loads the image...
}

function setup() {
  createCanvas(400, 400); // Canvas size...
  background(0); // Color of Canvas Background...
  //Removed "NoStroke" because it looks kind of cool with the strokes of the shapes
}

function draw() {
  x = random(width); // Randomly select an x-coordinate between 0 and the canvas width...
  y = random(height); // Randomly select a y-coordinate between 0 and the canvas height...
  var c = img.get(x, y); // Gets the color of the pixel from the image...

  fill(c[0], c[1], c[2], 10); 
  // Change transperancy to 10...

  rect(x, y, 30, 30); // Draw a rectangle at random positions...
}
