// Created folder for image because image outside the filepath doesn't work for reasons I don't know...?

var img, x, y; // Declares Variables...

function preload() {
  // Loads the image...
  img = loadImage("img/blacksquare.jpg");
}

function setup() {
  createCanvas(400, 400); // Sets the Canvas Size...
  noStroke(); // Disables stroke of any Shape
}

function draw() {
  background(0);

  // Set x and y to the current mouse coordinates...
  x = mouseX; // Get the x-coordinate of the mouse...
  y = mouseY; // Get the y-coordinate of the mouse...

  // Display the loaded image...
  image(img, 0, 0);

  // Gets the color of the pixel from the canvas at the current mouse position...
  // This includes reading the image, which has already been drawn to the canvas...
  var c = get(x, y);


  fill(c);  // Use the sampled color to set the fill color for the ellipse...

  ellipse(x, y, 50, 50);  // Draws an ellipse at the mouse position or when hovered with a diameter of 50 pixels...
}
